### ISSUE TITLE
Data and labels for the material-classification code

### ISSUE THREAD

**Issue by nneshov** [objectfolder/material-classification#1]
Hello, and thank you for sharing your great work! 
Could you please explain, how one can obtain the following dataset and labels, set in the main.py
parser.add_argument("--data_location", type=str, default='../DATA_new')
parser.add_argument("--split_location", type=str, default='../DATA_new/split.json')
Is it enough to download the original data provided in https://objectfolder.stanford.edu/objectfolder2-0-download and set the paths accordingly or some preparation is necessary?

**Comment by Nano1337** [comment]
Same question as above. Assuming we're using the ObjectFolder-Real that contains videos, how do we preprocess the videos to  extract image frames to classify according to the dataset code?
